---
name: CI

# yamllint disable-line rule:truthy
on:
  push:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        arch:
          - aarch64
          - amd64

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        uses: home-assistant/builder@6cb4fd3d1338b6e22d0958a4bcb53e0965ea63b4
        with:
          image: ${{ matrix.arch }}
          args: |
            --${{ matrix.arch }} \
            --target /data/ser2net \
            --addon
