---
name: Deploy

# yamllint disable-line rule:truthy
on:
  release:
    types:
      - published
  workflow_run:
    workflows:
      - CI
    branches:
      - main
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy:
    if: >
      github.event_name == 'release' ||
      github.event_name == 'workflow_dispatch' ||
      (
        github.event_name == 'workflow_run' &&
        github.event.workflow_run.conclusion == 'success'
      )

    strategy:
      matrix:
        include:
          - arch: aarch64
            runs-on: ubuntu-24.04-arm
          - arch: amd64
            runs-on: ubuntu-24.04

    runs-on: ${{ matrix.runs-on }}

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and publish
        uses: home-assistant/builder@6cb4fd3d1338b6e22d0958a4bcb53e0965ea63b4
        with:
          image: ${{ matrix.arch }}
          args: |
            --${{ matrix.arch }} \
            --target /data/ser2net \
            --image "ser2net" \
            --docker-hub "ghcr.io/${{ github.repository_owner }}" \
            --addon

      - name: Dispatch repository update
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.DISPATCH_TOKEN }}
          repository: vinzcoyote/repository-edge
          event-type: update
          client-payload: '{"addon": "ser2net"}'
